format = """
$directory\
$git_branch\
$git_status\
$c\
$rust\
$golang\
$python\
$nodejs\
$lua\
$cmd_duration\
$line_break\
$character"""

[character]
success_symbol = "[>](bold #7fdbca)"
error_symbol = "[>](bold #ef5350)"

[directory]
style = "#82aaff"
truncation_length = 3
truncate_to_repo = true

[git_branch]
format = "[$symbol$branch]($style) "
symbol = " "
style = "#c792ea"

[git_status]
format = '([$all_status$ahead_behind]($style) )'
style = "#ecc48d"
modified = "~"
untracked = "?"
staged = "+"
deleted = "-"

[cmd_duration]
format = "[$duration]($style) "
style = "#5f7e97"
min_time = 2_000

[c]
format = "[$symbol($version)]($style) "
symbol = " "
style = "#82aaff"

[rust]
format = "[$symbol($version)]($style) "
symbol = " "
style = "#ef5350"

[golang]
format = "[$symbol($version)]($style) "
symbol = " "
style = "#7fdbca"

[python]
format = "[$symbol($version)]($style) "
symbol = " "
style = "#ecc48d"

[nodejs]
format = "[$symbol($version)]($style) "
symbol = " "
style = "#22da6e"

[lua]
format = "[$symbol($version)]($style) "
symbol = " "
style = "#82aaff"
