format = """
$directory\
$git_branch\
$git_status\
$c\
$rust\
$golang\
$python\
$nodejs\
$lua\
$cmd_duration\
$line_break\
$character"""

[character]
success_symbol = "[❯](bold #DFAC70)"
error_symbol = "[❯](bold #9C6D6F)"

[directory]
style = "#E1C4AA"
truncation_length = 3
truncate_to_repo = true

[git_branch]
format = "[$symbol$branch]($style) "
symbol = " "
style = "#B58AAE"

[git_status]
format = "([$all_status$ahead_behind]($style) )"
style = "#B29098"
modified = "~"
untracked = "?"
staged = "+"
deleted = "-"

[cmd_duration]
format = "[$duration]($style) "
style = "#7477A1"
min_time = 2_000

[c]
format = "[$symbol($version)]($style) "
symbol = " "
style = "#7C8AC0"

[rust]
format = "[$symbol($version)]($style) "
symbol = " "
style = "#9C6D6F"

[golang]
format = "[$symbol($version)]($style) "
symbol = " "
style = "#6FA89E"

[python]
format = "[$symbol($version)]($style) "
symbol = " "
style = "#DFAC70"

[nodejs]
format = "[$symbol($version)]($style) "
symbol = " "
style = "#8FA17A"

[lua]
format = "[$symbol($version)]($style) "
symbol = " "
style = "#7C8AC0"
