background {
    path = ~/Pictures/wallpapers/wallhaven-polllj.jpg
    blur_passes = 2
    blur_size = 6
    noise = 0.02
    contrast = 0.9
    brightness = 0.6
}

general {
    hide_cursor = false
}

input-field {
    monitor =
    size = 250, 55
    outline_thickness = 0
    dots_size = 0.25
    dots_spacing = 0.3
    hide_input = true
    outer_color = rgba(00000000)
    inner_color = rgba(00000000)
    font_color = rgb(E1E9F2)
    check_color = rgb(DFAC70)
    fail_color = rgb(9C6D6F)
    placeholder_text =
    fail_text = <span foreground="##9C6D6F">$FAIL <b>($ATTEMPTS)</b></span>
    font_family = JetBrainsMono Nerd Font
    position = 0, -20
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    color = rgb(E1E9F2)
    font_size = 90
    font_family = JetBrainsMono Nerd Font
    position = 0, 160
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] echo "$(date +"%A, %d %B")"
    color = rgb(7477A1)
    font_size = 20
    font_family = JetBrainsMono Nerd Font
    position = 0, 80
    halign = center
    valign = center
}
